### ISSUE TITLE
No such file or directory: './config/openedx/templates/lms.env.json.templ'

### ISSUE THREAD

**Issue by shohrehahvar** [regisb/openedx-docker#60] opened 2018-09-04 10:03 UTC
Hello and thanks for your work :)

We have one error when we use your 1-click method :
No such file or directory: './config/openedx/templates/lms.env.json.templ'

Please find bellow the details.

:~/openedx-docker$ sudo make all

docker run --rm -it --volume="/config:/openedx/config" \

    -e USERID=$(id -u) -e SILENT= -e ACTIVATE_HTTPS= -e ACTIVATE_XQUEUE= \

    regis/openedx-configurator====================================

     Interactive configuration

====================================

Your website domain name for students (LMS). (default: "openedxdemo.org"):

Your website domain name for teachers (CMS). (default: "studio.openedxdemo.org"):

Platform name/title (default: "My Open edX Demo"):Configuration values were saved to  /openedx/config/config.json

Traceback (most recent call last):

 File "./configure.py", line 156, in <module>

   main()

 File "./configure.py", line 77, in main

   args.func(args)

 File "./configure.py", line 135, in substitute

   with codecs.open(args.src, encoding='utf-8') as fi:

 File "/usr/lib/python3.6/codecs.py", line 897, in open

   file = builtins.open(filename, mode, buffering)

FileNotFoundError: [Errno 2] No such file or directory: './config/openedx/templates/lms.env.json.templ'

Makefile:32: recipe for target 'configure' failed

make: *** [configure] Error 1

Message Input

Thanks,

Best regards,

**Comment by regisb** [comment] 2018-09-04 10:12
This is a duplicate of issue #50. tl;dr: try to run docker without sudo.

**Closed** 2018-09-04 10:14 UTC
