### ISSUE TITLE
Error on xqueue and xqueue-consumer.

### ISSUE THREAD

**Issue by raviVeeraghanta** [regisb/openedx-docker#32] opened 2018-06-07 13:33 UTC
Hi,
First of all a big thank you for putting this together.
I cloned the Git repository a few minutes ago and have python,docker (17.12.1) and docker-compose (1.21.2) running on Ubuntu 18.04
Getting these errors when doing a make all
ERROR: for xqueue_consumer  pull access denied for regis/openedx-xqueue, repository does not exist or may require 'docker login'

ERROR: for xqueue  pull access denied for regis/openedx-xqueue, repository does not exist or may require 'docker login'
ERROR: pull access denied for regis/openedx-xqueue, repository does not exist or may require 'docker login'
Do let me know if you need any more debug information.

**Comment by regisb** [comment] 2018-06-08 03:48
Hi! This is a duplicate of issue #33. Please check it out for a temporary fix. I'm working on a more permanent fix!

**Comment by regisb** [comment] 2018-06-08 13:55
This should be fixed now \o/

**Closed by regisb** 2018-06-08 13:55 UTC
