### ISSUE TITLE
Is there a way to install https://github.com/ibleducation/jupyter-edx-grader-xblock?

### ISSUE THREAD

**Issue by roblhibbard** [regisb/openedx-docker#84] opened 2018-11-02 14:38 UTC
It looks like this is setup to install on a standard edX install. Just checking to see if it could be installed on this build. 

thank you,

Robert

**Comment by regisb** [comment] 2018-11-02 15:17
I am most certain it can. Have you tried it?

**Comment by regisb** [comment] 2018-11-02 15:17
Duplicate of #36

**Comment by roblhibbard** [comment] 2018-11-02 15:39
I did try, but was not sure how to implement. I am new to docker and edX. I ran into issues here with the database migration.
`Database Migration
Run the following as a root user to create the necessary database models:

sudo su edxapp -s /bin/bash
cd ~/edx-platform
source ../venvs/edxapp/bin/activate
./manage.py cms migrate xblock_jupyter_graded --settings=aws`

could not find a work around for this.

thank you,

Robert

**Comment by roblhibbard** [comment] 2018-11-02 17:16
thanks for the reply,
I will give that a go and let you know how it turns out.

**Comment by roblhibbard** [comment] 2018-11-02 21:34
One more quick question, do I need to be using a ubuntu version 16.04 to make upgrade the edx_platform I forked? I am using Ubuntu 18.04, I am getting an error.
`Makefile:42: recipe for target 'upgrade' failed
make: *** [upgrade] Error 1
`

**Comment by regisb** [comment] 2018-11-05 08:48
Can you please post the complete error log? Otherwise it's difficult to understand the full issue. But I don'work with Ubuntu 18.04 and I believe I can run `make upgrade` with no problem.

**Comment by roblhibbard** [comment] 2018-11-06 17:15
sorry for the late reply,

after more research it looks like this xblock will not run on the Hawthorn version. I loaded ubuntu 16.04 and the Ginkgo version and it allowed it to install, but still seemed to cause some errors. Something with django version 1.9. So I have scrapped this plugin completely until a possible upgrade in the future. So I am loading this version back onto a ubuntu 16.04 server.

**Comment by regisb** [comment] 2018-11-08 08:08
Ok, so I'll just close this issue. Thanks for investigating!

**Closed by regisb** 2018-11-08 08:08 UTC

**Comment by roblhibbard** [comment] 2019-01-06 18:56
Hello again,

It looks like they have made this available for the Hawthorne. https://github.com/ibleducation/jupyter-edx-grader-xblock/pull/8

Would I use the same method described above for this previous issue, to give this another try. I did use the private.txt to pull the git+https://github.com/ibleducation/jupyter-edx-grader-xblock.git,  I will still need to add the other information to the following:

LMS/CMS Setup
In the following two files:
<pre>
/edx/app/edxapp/edx-platform/lms/urls.py
/edx/app/edxapp/edx-platform/cms/urls.py
Add the following to the bottom of each file:

# Jupyter Graded XBlock Endpoints
urlpatterns += (
    url(r'^api/jupyter_graded/', include('xblock_jupyter_graded.rest.urls')),
)
In the following two files:

/edx/app/edxapp/edx-platform/lms/envs/common.py
/edx/app/edxapp/edx-platform/cms/envs/common.py
Add the following at the bottom of the INSTALLED_APPS section:

    # Jupyter Notebook Graded XBlock
    'xblock_jupyter_graded',
</pre>

thank you,

Robert

**Comment by regisb** [comment] 2019-01-06 20:32
Yes, this looks about right. Note that since you fork the edx-platform repository, you don't really need to modify the private.txt requirements file; instead, you can directly modify the edx-platform/requirements/ files. You decide :)

**Comment by roblhibbard** [comment] 2019-01-06 20:38
Thanks I will give that a try when I get back home.

**Comment by awantik** [comment] 2020-04-01 17:57
I loved tutor. We are replacing our current LMS by openedx because of the tutor.
@regisb, Is there a better way to view ipynb directly using tutor now?

**Comment by regisb** [comment] 2020-04-01 18:37
Hi @awantik! As much as I appreciate your enthusiasm, please don't comment on closed issues. This is a conversation that is better suited for the official forums: https://discuss.overhang.io

As far as I know, there is no straightforward and full-featured way to view ipython or jupyter notebooks in Open edX. This is an oft-requested feature, but it requires some development time. If you're interested in sponsoring this effort, maybe you could band with a few other providers.

**Comment by ZoranPandovski** [comment] 2020-04-01 18:45
@roblhibbard Did you manage to enable this plugin? I did all of the above(required) steps:

- Extend edx-platform, added required changes in CMS and LMS
- Change Tutor Docker to point to the fork
- Re-run tutor local quickstart ( In the logs xblock_jupyter_graded is added in Operations to perform)
 There are no errors while building the new image, and when I run the studio the Advanced option is not displayed.
